## Python For Machine Learning Fall 2025
---
# Multivariate Linear Regression

## Numpy for Multivariate Linear Regression

NumPy is a powerful library for numerical operations in Python. Its main feature is the `ndarray`, a multi-dimensional array object that is highly efficient for performing mathematical calculations. In machine learning, we'll use NumPy to handle our data, which is often represented as matrices and vectors.

In [2]:
import numpy as np

The most straightforward way to create a NumPy array is to pass a Python list or tuple to the `np.array()` function. This is especially useful for creating arrays with specific initial values. Create a 1D array (vector)

In [4]:
np.array([1 ,2, 3, 4])

array([1, 2, 3, 4])

To create a multi-dimensional array, pass a nested list or tuple.

In [6]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

NumPy provides several functions for creating arrays with placeholder or structured data. These are more efficient than creating Python lists first, especially for large arrays.

`np.zeros()`: Creates an array filled with zeros. You must specify the shape.

In [10]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

`np.ones()`: Creates an array filled with ones.

In [11]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

`np.full()`: Creates an array of a given shape filled with a specified value.

`np.eye()`: Creates a 2-D identity matrix, which has ones on the main diagonal and zeros elsewhere.

In [15]:
threes = np.full((4, 5), 3)

`np.identity(n)`: Used only for creating a square identity matrix.

In [13]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.diag() is a NumPy function that either extracts a diagonal from a 2D array or creates a 2D diagonal array from a 1D array.

In [17]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

There are three common ways to transpose a NumPy matrix.

`.T` attribute

In [33]:
my_matrix = np.array([[2 ,1, 3], [0, 2, 4], [1, 1, 2]])

my_matrix.T

array([[2, 0, 1],
       [1, 2, 1],
       [3, 4, 2]])

`.transpose()` method

In [28]:
my_matrix.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

`np.transpose()` function

In [29]:
np.transpose(my_matrix)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

`np.linalg.inv()` is a NumPy function used to calculate the multiplicative inverse of a matrix.

In [34]:
np.linalg.inv(my_matrix)

array([[ 0. , -0.5,  1. ],
       [-2. , -0.5,  4. ],
       [ 1. ,  0.5, -2. ]])

In Numpy, you can perform matrix multiplication using either the `@` operator or the `np.matmul()` function.

In [38]:
matrix_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

my_matrix @ matrix_2

array([[27, 33, 39],
       [36, 42, 48],
       [19, 23, 27]])

In [39]:
np.matmul(my_matrix, matrix_2)

array([[27, 33, 39],
       [36, 42, 48],
       [19, 23, 27]])

In Numpy, you can perform element-wise multiplication using the operator * or the np.multiply() function.

In [40]:
my_matrix * 2

array([[4, 2, 6],
       [0, 4, 8],
       [2, 2, 4]])

In [41]:
np.multiply(my_matrix, 2)

array([[4, 2, 6],
       [0, 4, 8],
       [2, 2, 4]])

`np.concatenate()` function or its convinient object `np.c_` can concatenate two or more Numpy arrays.

In [47]:
np.concatenate(([1, 2, 3], [4, 5, 6]))

array([1, 2, 3, 4, 5, 6])

For 2D arrays, you must specify the `axis` to control whether the arrays are stacked vertically (along rows) or horizontally (along columns).

In [48]:
np.concatenate((my_matrix, matrix_2), axis=0)

array([[2, 1, 3],
       [0, 2, 4],
       [1, 1, 2],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

For an Numpy array, method `.reshape()` returns a new array with the same data but a different shape.

In [61]:
np.reshape(my_matrix, [9, 1])

array([[2],
       [1],
       [3],
       [0],
       [2],
       [4],
       [1],
       [1],
       [2]])

A very useful feature of .reshape() is the use of -1 as a placeholder. This tells NumPy to automatically calculate the dimension for that axis based on the total number of elements and the other dimensions you've specified.

In [57]:
np.reshape(my_matrix, -1)

array([2, 1, 3, 0, 2, 4, 1, 1, 2])

Now we have everything we need to finish the calculation fo multivariable linear regression.

## From univariate to Multivariate Linear Regression

Recall that univariate linear regression uses a single feature to predict a target variable, described by the equation:

$$
y = m x + b
$$

But what happens when the target is influenced by multiple factors? We extend our model to **Multiple Linear Regression**, the single output version of **Multivariate linear regression**, where the equation becomes:

$$
y = \theta_0 + \theta_1 x_1 + \theta_2 x_2 + \dots + \theta_n x_n
$$

Here, $y$ is the target value, $\theta_0$ is the intercept, and $\theta_1, \dots, \theta_n$ are the coefficients (weights) for each feature $x_1, \dots, x_n$.

### Agreement on Symbols

To prevent confusion, we need to establish more precise symbol conventions, which is different from how we handle single-variable situations.

- We represent scalars with lowercase letters or Greek letters, such as $t$ or $\alpha$.
- Use bold, lowercase letters or bold Greek letters for vectors, like $\mathbf{x}$. Their elements are written as $x_i$. Note that a bold lowercase letter with a subscript, such as $\mathbf{x_1}$ and $\mathbf{x_2}$, represents two different constant vectors. By default, vectors are column vectors; a row vector is a transpose of a column vector, written as $\mathbf{x^T}$.
- Matrices are represented by capital letters such as $A$ and $\Sigma$. Their elements are shown with lowercase letters, such as $a_{ij}$. Capital letters with subscripts, like $A_1$ and $A_2$, indicate different constant matrices.

## The Matrix Form

Multiple linear regression has vectors as samples and the weights are also vectors. To handle the more complex model, the more compact **matrix form** is a better way.

Let's define our matrices:

-   **Feature Matrix $X$:** An $m \times (n+1)$ matrix where $m$ is the number of training examples and $n$ is the number of features. We add a column of ones for the intercept term $\theta_0$.
-   **Coefficient Vector $\theta$:** A vector of size $(n+1) \times 1$ containing all the coefficients, including the intercept.
-   **Target Vector $y$:** An $m \times 1$ vector of the target values.

The prediction can then be calculated as a dot product:

$$
\hat{y} = X \theta
$$

## Data Preparation

We will use a typical house price prediction model for this experiment. https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html

To start, we will select a few features from the dataset.

Next, we will add a column where all values are 1.

The last step is to process the prediction target.

The model is very compact when represented in its matrix form.

## The Normal Equation

The **Normal Equation** provides a direct, analytical solution to find the optimal values for $\theta$ without needing to iterate. The formula is:

$$
\mathbf{\theta} = (X^T X)^{-1} X^T \mathbf{y}
$$

Where:
-   $X^T$ is the transpose of the feature matrix $X$.
-   $X^T X$ is the dot product of the transpose of $X$ and $X$.
-   $(X^T X)^{-1}$ is the inverse of that result.
-   $\mathbf{y}$ is the target vector.


Here is how we get the result
Note that the linear function (model) as follows:
$$
h_{\mathbf{\theta}}(x_1, x_2,..., x_n) = \theta_0\cdot 1+\theta_1x_1+,...,\theta_nx_n
$$
Note $\mathbf{x}=[x_1, x_2,..., x_n]$, then we have:
$$
h_{\mathbf{\theta}}(\mathbf{x})=\mathbf{x}\mathbf{\theta}
$$
Note that:
$$
X= \begin{matrix} \mathbf{x_1^T} \\ \mathbf{x_2^T} \\ ... \\ \mathbf{x_m^T} \end{matrix}
$$
We can simplify the calculation as
$$
\mathbf{y}=X\mathbf{\theta}
$$
Then we can define the loss function as:
$$
J(\mathbf{\theta})=\frac{1}{2}(X\mathbf{\theta}-\mathbf{y})^T(X\mathbf{\theta}-\mathbf{y})
$$
Make the derivate of $J$ regarding $\mathbf{\theta}$ equals to $0$, we get
$$
\frac{\partial}{\partial \mathbf{\theta}}J(\mathbf{\theta})=X^T(X\mathbf{\theta}-\mathbf{y})=0
$$
Thus, we get:
$$
\mathbf{\theta}=(X^T X)^{-1} X^T \mathbf{y}
$$

Calculate coefficients using the Normal Equation
Using np.linalg.inv for matrix inversion and @ for dot product

Let's check if the predictions are accurate.

Let's see if `sklearn` performs better.

Gradient Descent

The problem can also be solved using gradient descent (of course). Slightly different from the normal equation, we have:
$$
J(\mathbf{\theta})=\frac{1}{2}(X\mathbf{\theta}-\mathbf{y})^T(X\mathbf{\theta}-\mathbf{y})
$$
and thus, the gradient vector is:
$$
\frac{\partial}{\partial \mathbf{\theta}}J(\mathbf{\theta})=\frac{1}{m}X^T(X\mathbf{\theta}-\mathbf{y})
$$



Similar to the univariate linear regression, we implement the algorithm block by block.

We will implement the loss function first, following the same basic steps as single-variable linear regression.

The next step is to implement how to calculate the gradient.

Initialize the model's parameters randomly.

Define the hyperparameters and implement the training loop.

Let's evaluate the model's performance.

## Normal Equation vs. Gradient Descent

-   **Normal Equation:**
    -   **Pros:** Direct solution, no need to choose a learning rate or number of iterations.
    -   **Cons:** Computationally expensive for large datasets ($O(n^3)$ due to matrix inversion).

-   **Gradient Descent:**
    -   **Pros:** More scalable for large datasets.
    -   **Cons:** Requires tuning hyperparameters like learning rate and number of iterations.

For many real-world problems, especially with massive datasets, libraries like scikit-learn use optimized algorithms (often based on gradient descent) for efficiency.